Controllers/FormsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Security.Claims;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;
using Microsoft.AspNetCore.Authorization;

namespace tp_nt1a_1.Controllers
{
    public class FormsController : Controller
    {
        private readonly ScheduleDbContext _context;

        public FormsController(ScheduleDbContext context)
        {
            _context = context;
        }

        // GET: Forms
        [Authorize(Roles = "Administrador, Profesional")]
        public async Task<IActionResult> Index()
        {
            var scheduleDbContext = _context.Forms.Include(f => f.Patient);
            return View(await scheduleDbContext.ToListAsync());
        }

        // GET: Forms/Details/5
        [Authorize(Roles = "Administrador, Profesional")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Forms
                .Include(f => f.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }

        // GET: Forms/Create
        [AllowAnonymous]
        public IActionResult Create()
        {
            var model = new Form();
            if (User.IsInRole(nameof(Role.Paciente)))
            {
                var patientId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                var patient = _context.Patients.Find(patientId);
                model.Email = patient.Email;
                model.FirstName = patient.FirstName;
                model.LastName = patient.LastName;
                model.PatientId = patientId;
            }

            return View(model);
        }

        // POST: Forms/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public async Task<IActionResult> Create(Form form)
        {
            if (ModelState.IsValid)
            {
                form.Id = Guid.NewGuid();
                form.Read = false;

                if (User.IsInRole(nameof(Role.Paciente)))
                {
                    var patientId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
                    var patient = _context.Patients.Find(patientId);
                    form.PatientId = patientId;
                    form.Email = patient.Email;
                    form.FirstName = patient.FirstName;
                    form.LastName = patient.LastName;
                }
                form.Date = DateTime.Now;

                _context.Add(form);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index","Home");
            }
            
            return View(form);
        }

        [HttpPost]
        [Authorize(Roles = "Profesional,Administrador")]
        public async Task<IActionResult> ChangeReadStatus(Guid formId)
        {
            var form = this._context.Forms.FirstOrDefault(f => f.Id == formId);

            form.Read = !form.Read;
            await this._context.SaveChangesAsync();
            return this.RedirectToAction(nameof(Index));
        }


        

        // GET: Forms/Delete/5
        [Authorize(Roles = "Administrador, Profesional")]
        public async Task<IActionResult> Delete(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var form = await _context.Forms
                .Include(f => f.Patient)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (form == null)
            {
                return NotFound();
            }

            return View(form);
        }

        // POST: Forms/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrador, Profesional")]
        public async Task<IActionResult> DeleteConfirmed(Guid id)
        {
            var form = await _context.Forms.FindAsync(id);
            _context.Forms.Remove(form);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool FormExists(Guid id)
        {
            return _context.Forms.Any(e => e.Id == id);
        }
    }
}

Controllers/TurnsController.cs
using System;
using System.Collections;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using tp_nt1.Database;
using tp_nt1.Models;

namespace tp_nt1a_1.Controllers
{
    [Authorize]
    public class TurnsController : Controller
    {
        private readonly ScheduleDbContext _context;

        public TurnsController(ScheduleDbContext context)
        {
            _context = context;
        }

        // GET: Turns
        [Authorize(Roles = "Administrador")]
        public async Task<IActionResult> Index()
        {
            var scheduleDbContext = _context.Turns.Include(t => t.Patient).Include(t => t.Professional);

            foreach (var i in scheduleDbContext)
            {

                if (i.Date < DateTime.Now)
                {
                    i.Active = false;
                    await _context.SaveChangesAsync();

                }
            }
                return View(await scheduleDbContext.ToListAsync());
        }

        [Authorize(Roles = "Paciente")]
        public async Task<IActionResult> MyTurns()
        {
            var patientId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var turns = _context.Turns.Include(t => t.Professional).Where(t => t.Patient.Id == patientId);

            foreach (var i in turns){
              
                if (i.Date < DateTime.Now)
                {
                    i.Active = false;
                    await _context.SaveChangesAsync();

                }
            }
            return View(await turns.ToListAsync());
        }

        [Authorize(Roles = "Paciente")]
        public async Task<IActionResult> MyTurnsCantCreate()
        {
            var patientId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var turns = _context.Turns.Include(t => t.Professional).Where(t => t.Patient.Id == patientId);
            return View(await turns.ToListAsync());
        }

        [Authorize(Roles  = "Profesional")]
        public async Task<IActionResult> ProfessionalTurns()
        {
            var professionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var turns = _context.Turns.Include(t => t.Patient).Where(t => t.Professional.Id == professionalId && t.Date > DateTime.Now);
            return View(await turns.ToListAsync());
        }


        [HttpGet]
        [Authorize (Roles = "Profesional")]
        public async Task<IActionResult> Balance()
        {
            var professionalId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var turns = _context.Turns.Include(t => t.Patient)
                                      .Include(t => t.Professional)
                                      .ThenInclude(t => t.MedicalService)
                                      .Where(t => t.Professional.Id == professionalId && t.Date.Month == DateTime.Now.Month && t.Confirmed == true);

            List<Turn> turnsTotal = turns.ToList();

            var totalPrice = turnsTotal.Sum(t => t.Professional.MedicalService.Price);
            ViewData["Price"] = totalPrice;

            return View(await turns.ToListAsync());
        }

        [HttpPost]
        [Authorize(Roles = "Profesional,Administrador")]
        public async Task<IActionResult> ChangeConfirmedStatus(Guid turnId)
        {
            var turn = this._context.Turns.FirstOrDefault(t => t.Id == turnId);

            turn.Confirmed = !turn.Confirmed;
            await this._context.SaveChangesAsync();

            if (User.IsInRole(nameof(Role.Profesional)))
            {
                return this.RedirectToAction(nameof(ProfessionalTurns));
            } 
                return this.RedirectToAction(nameof(Index));
                           
        }


        // GET: Turns/Details/5
        [Authorize(Roles = "Administrador, Profesional, Paciente")]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var turn = await _context.Turns
                .Include(t => t.Patient)
                .Include(t => t.Professional)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (turn == null)
            {
                return NotFound();
            }

            return View(turn);
        }


        [Authorize(Roles = "Paciente")]
        public IActionResult SelectMedicalService()
        {
            var patientId = Guid.Parse(User.FindFirstValue(ClaimTypes.NameIdentifier));
            var turnsPatient = _context.Turns.Where(t => t.Patient.Id == patientId && t.Active == true);
            if (turnsPatient.Count() != 0)
            {
                ModelState.AddModelError(nameof(Patient.Turns), "Ya tiene un turno activo asignado.");
                return RedirectToAction(nameof(MyTurnsCantCreate));
            }

            else
            {
                ViewData["MedicalServiceId"] = new SelectList(_context.MedicalServices, "Id", "Name");
            }

            return View();
        }


        [Authorize(Roles = "Paciente")]
        public IActionResult SelectProffesional(Guid medicalServiceId)
        {

            TempData["medicalServiceId"] = medicalServiceId;
            ViewData["professionalId"] = new SelectList(_context.Professionals.Where(p => p.MedicalServiceId==medicalServiceId), "Id", nameof(Professional.FullName));
            return View();

        }


        // GET: Turns/Create
        [Authorize(Roles = "Paciente")]
        public IActionResult SelectDate(Guid professionalId, Guid medicalServiceId)
        {
            TempData["medicalServiceId"] = medicalServiceId;
            TempData["professionalId"] = professionalId;

            var medicalService = _context.MedicalServices.FirstOrDefault(medicalService => medicalService.Id == medicalServiceId);
            var medicalServiceName = medicalService.Name;
            ViewBag.medicalServiceName = medicalServiceName;

            var professional = _context.Professionals.FirstOrDefault(professional => professional.Id == professionalId);
            var professionalName = professional.FullName;
            ViewBag.professionalName = professionalName;

            var startTimeProfessional = professional.StartTime;
            var endTimeProfessional = professional.EndTime;
            var durationTurn = professional.MedicalService.Duration;
            var today = DateTime.Today.AddDays(1);
            var todayMoreSeven = today.AddDays(7);
            List<SelectList> listItems = new List<SelectList>();
            
            for (DateTime i = today; i < todayMoreSeven; i.AddDays(1))
                {
                    for (DateTime o = startTimeProfessional; o < endTimeProfessional; o.AddMinutes(durationTurn))
                    {
                     var diaStr = i.ToString("dd/MM/yyyy") + " " + o.ToString("HH:mm");

                    o = o.AddMinutes(durationTurn);
                    if (o < endTimeProfessional)
                    {

                        listItems.Add(new SelectList(listItems, diaStr, diaStr));
                        
                    }
                    
                }
                
                i = i.AddDays(1);
                startTimeProfessional = professional.StartTime;

                }

            var turnsProfessional = _context.Turns.Where(t => t.Professional.Id == professionalId && t.Active == true);

            foreach (var t in turnsProfessional)
            {
                var actulTurn = t.Date;
                var turnStr = actulTurn.ToString("dd/MM/yyyy HH:mm");
                    
                foreach (var i in listItems.ToList())
                {
                    var listTurn = i.DataTextField;
                    if (turnStr == listTurn)
                    {
                        listItems.Remove(i);
                          
                    }
                }
            }

            ViewData["date"] = new SelectList(listItems, "DataValueField" , "DataTextField");
             
            return View();
        }

        [Authorize(Roles = "Paciente")]
        public IActionResult ConfirmTurn(Guid professionalId, Guid medicalServiceId, String date)
        {
            TempData["medicalServiceId"] = medicalServiceId;
            TempData["professionalId"] = professionalId;
            TempData["date"] = date;

            var medicalService = _context.MedicalServices.FirstOrDefault(medicalService => medicalService.Id == medicalServiceId);
            var medicalServiceName = medicalService.Name;
            ViewBag.medicalServiceName = medicalServiceName;

            var professional = _context.Professionals.FirstOrDefault(professional => professional.Id == professionalId);
            var professionalName = professional.FullName;
            ViewBag.professionalName = professionalName;

            var dateStr = date;
            var dateTime = DateTime.ParseExact(dateStr, "dd/MM/yyyy HH:mm", System.Globalization.CultureInfo.InvariantCulture);
            ViewBag.dateTime = dateTime;
            
            return View();
        }


        // POST: Turns/Create
        //To protect from overposting attacks, enable the specific properties you want to bind to, for 
        //more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Paciente")]
        public async Task<IActionResult> Create(Guid professionalId, Guid medicalServiceId, DateTime date, Turn turn)
        {
            TempData["medicalServiceId"] = medicalServiceId;
            TempData["professionalId"] = professionalId;
            TempData["date"] = date;

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agenda De Turnos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link href="~/lib/alertifyjs/css/alertify.min.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <partial name="~/Views/Shared/_Navbar.cshtml" />
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - tp_nt1 
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/lib/alertifyjs/alertify.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)

    @if (TempData["LoggedIn"] as bool? ?? false)
    {
<script>
            alertify.success("Bienvenido @User.FindFirstValue(ClaimTypes.GivenName) !!!");
</script>
    }
</body>
</html>

Views/Shared/_LayoutLogin.cshtml
<!DOCTYPE html>
<html lang="es-ar">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Agenda De Turnos</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

Views/Shared/_MedicalServicesPartial.cshtml
@model IEnumerable<tp_nt1.Models.MedicalService>

<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingOne">
            <h2 class="mb-0">
                <button class="btn btn-link" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                   Cartilla De Prestaciones
                </button>
            </h2>
        </div>

        <div id="collapseOne" class="collapse show" aria-labelledby="headingOne" data-parent="#accordionExample">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.Name)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Description)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Duration)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.Price)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Description)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.Duration) minutos
                                </td>
                                <td>
                                    AR$ @Html.DisplayFor(modelItem => item.Price)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

Views/Shared/_Navbar.cshtml
<header>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
        <div class="container">
            <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">
                <img src="~/img/schedule.png" style="height:50px;" />
            </a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                <ul class="navbar-nav flex-grow-1">
                    @if (User.IsInRole(nameof(Role.Administrador)))
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admins" asp-action="Index">Administradores</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Professionals" asp-action="Index">Profesionales</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Patients" asp-action="Index">Pacientes</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="MedicalServices" asp-action="Index">Prestaciones</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Turns" asp-action="Index">Turnos</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Forms" asp-action="Index">Formularios De Consulta</a>
                        </li>
                    }
                </ul>
            </div>
            <ul class="navbar-nav">
                @if (User.Identity.IsAuthenticated)
                {
                    <li class="dropdown">
                        <button class="btn dropdown-toggle" type="button" id="menuOpciones" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Hola, @User.FindFirstValue(ClaimTypes.GivenName) <span class="caret ml-1"></span>
                        </button>
                        <div class="dropdown-menu" aria-labelledby="menuOpciones">
                            @if (User.IsInRole(nameof(Role.Profesional)))
                            {
                                <a class="dropdown-item" asp-controller="Turns" asp-action="ProfessionalTurns">
                                    Mis Turnos Asignados
                                </a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Forms" asp-action="Index">
                                    Consultas Recibidas
                                </a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Turns" asp-action="Balance">
                                    Balance
                                </a>
                                <hr />

                            }
                            else if (User.IsInRole(nameof(Role.Paciente)))
                            {
                                <a class="dropdown-item" asp-controller="Patients" asp-action="EditMe">
                                    Editar Mis Datos
                                </a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Turns" asp-action="MyTurns">
                                    Mis Turnos
                                </a>
                                <hr />
                                <a class="dropdown-item" asp-controller="Forms" asp-action="Create">
                                    Formulario De Consulta
                                </a>
                                <hr />
                            }
                            <form id="logoutForm" method="post" asp-controller="Access" asp-action="LogOut">
                                <button type="submit" class="dropdown-item">
                                    Salir
                                </button>
                            </form>
                        </div>
                    </li>

                }
                else
                {
            <li class="ml-1">
                <a asp-controller="Access" asp-action="Login" class="btn btn-outline-primary">
                    Ingresar
                </a>
                <a asp-controller="Access" asp-action="Register" class="btn btn-primary">
                    Registrarse
                </a>
                <a asp-controller="Forms" asp-action="Create" class="btn btn-link">
                    Consulta
                </a>
            </li>              
                }
            
            </ul>
        </div>
    </nav>
</header>

Views/Shared/_ProfessionalsPartial.cshtml
@model IEnumerable<tp_nt1.Models.Professional>

<div class="accordion" id="accordionExample">
    <div class="card">
        <div class="card-header" id="headingThree">
            <h2 class="mb-0">
                <button class="btn btn-link collapsed" type="button" data-toggle="collapse" data-target="#collapseThree" aria-expanded="false" aria-controls="collapseThree">
                    Cartilla De Profesionales
                </button>
            </h2>
        </div>
        <div id="collapseThree" class="collapse" aria-labelledby="headingThree" data-parent="#accordionExample">
            <div class="card-body">
                <table class="table">
                    <thead>
                        <tr>
                            <th>
                                @Html.DisplayNameFor(model => model.MedicalService)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.FirstName)
                            </th>
                            <th>
                                @Html.DisplayNameFor(model => model.LastName)
                            </th>
                            <th></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr>
                                <td>
                                    @Html.DisplayFor(modelItem => item.MedicalService.Name)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.FirstName)
                                </td>
                                <td>
                                    @Html.DisplayFor(modelItem => item.LastName)
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>